# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c3233043b4107d1f0ed4ea91616cfdd0e5874b6895064aef2d050e22809e07755dc5d87e7a20a42103b2ed75e7e1cbe6a1b40db3fec59fe6d21f059b7514134

test:
  secret_key_base: 0dc5c7a93b6928d4fe8b07e2167888c1bed92a895507b0739b4e0d5fdd8acd9a12584961b9169385f224a559a1628f1e3c580c07e2cfbfde39ba705880a445b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
